const fs=require('fs'),p=require('path'),pw=require('C:/Users/KenSi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root=p.resolve(__dirname,'..');
(async()=>{const b=await pw.chromium.launch({channel:'msedge'});try{const page=await b.newPage();for(const [name,file] of [['z5ii','2c13dc56-86f8-49b2-98e5-f8c6c97e4735'],['z6','39328c33-319b-4353-af89-37d68419da8e'],['xt50','15af9567-e69b-4051-8852-c6f76937901f']]){
const data='data:image/png;base64,'+fs.readFileSync('C:/Users/KenSi/AppData/Local/Temp/codex-clipboard-'+file+'.png').toString('base64');const svg=await page.evaluate(async({data,name})=>{const img=new Image();img.src=data;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const g=c.getContext('2d');g.drawImage(img,0,0);const {data:d}=g.getImageData(0,0,c.width,c.height),w=c.width,h=c.height;let minX=w,minY=h,maxX=0,maxY=0;const colors=['#000000',...(name==='z5ii'?['#e00000']:[])],paths=[];
for(let channel=0;channel<colors.length;channel++){
 const sample=(x,y)=>{const i=(y*w+x)*4,r=d[i]/255,green=d[i+1]/255,blue=d[i+2]/255;return channel?Math.max(0,r-Math.max(green,blue)):1-Math.max(r,green,blue)};
 const segments=[];const key=pt=>pt.map(v=>v.toFixed(5)).join(',');const edges=[[0,1],[1,2],[2,3],[3,0]];
 for(let y=0;y<h-1;y++)for(let x=0;x<w-1;x++){const pts=[[x,y],[x+1,y],[x+1,y+1],[x,y+1]],v=pts.map(([a,b])=>sample(a,b)),cross=[];for(const [a,b] of edges){if((v[a]>=.5)!==(v[b]>=.5)){const t=(.5-v[a])/(v[b]-v[a]);cross.push([pts[a][0]+t*(pts[b][0]-pts[a][0]),pts[a][1]+t*(pts[b][1]-pts[a][1])]);}}for(let i=0;i+1<cross.length;i+=2)segments.push([cross[i],cross[i+1]]);}
 const links=new Map();segments.forEach((seg,i)=>seg.forEach(pt=>{const k=key(pt);if(!links.has(k))links.set(k,[]);links.get(k).push(i)}));const used=new Set(),loops=[];
 for(let i=0;i<segments.length;i++){if(used.has(i))continue;used.add(i);const pts=[segments[i][0],segments[i][1]];let end=pts[1];while(key(end)!==key(pts[0])){const next=(links.get(key(end))||[]).find(j=>!used.has(j));if(next===undefined)break;used.add(next);end=segments[next].find(pt=>key(pt)!==key(end));pts.push(end);}if(pts.length>10){pts.pop();loops.push(pts)}}
 let shape='';for(let points of loops){let area=0;for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];area+=a[0]*b[1]-b[0]*a[1]}if(Math.abs(area)<3)continue;
 // Two subpixel corner-cutting passes remove pixel stair steps without changing proportions.
 for(let pass=0;pass<2;pass++){const out=[];for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];out.push([.75*a[0]+.25*b[0],.75*a[1]+.25*b[1]],[.25*a[0]+.75*b[0],.25*a[1]+.75*b[1]])}points=out}
 for(const [x,y] of points){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}shape+='M'+points.map(pt=>pt.map(v=>v.toFixed(2)).join(' ')).join('L')+'Z';}
 paths.push('<path fill="'+colors[channel]+'" fill-rule="evenodd" d="'+shape+'"/>');}
 const x=Math.floor(minX)-1,y=Math.floor(minY)-1,width=Math.ceil(maxX)-x+1,height=Math.ceil(maxY)-y+1;return '<svg xmlns="http://www.w3.org/2000/svg" width="'+width+'" height="'+height+'" viewBox="'+[x,y,width,height].join(' ')+'">'+paths.join('')+'</svg>';
},{data,name});fs.writeFileSync(p.join(root,'assets','models',name+'.svg'),svg);console.log(name,svg.length);}
let s=fs.readFileSync(p.join(root,'polaroid.html'),'utf8');const sources=Object.fromEntries(['z5ii','z6','xt50'].map(k=>[k,'data:image/svg+xml;base64,'+fs.readFileSync(p.join(root,'assets','models',k+'.svg')).toString('base64')]));s=s.replace(/const MODEL_LOGO_SOURCES=.*?;\n/,'const MODEL_LOGO_SOURCES='+JSON.stringify(sources)+';\n');fs.writeFileSync(p.join(root,'polaroid.html'),s);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
