const fs=require('fs'),path=require('path'),assert=require('assert');
const pw=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/KenSi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=process.env.STUDIO_ROOT||'\\\\kensi_nas\\homes\\KenSi\\拍立得模擬器';
const base='file://kensi_nas/homes/KenSi/'+encodeURIComponent('拍立得模擬器')+'/';
function exifJpeg(jpeg,make,model,lens,params=true){
 const out=Buffer.alloc(4096);out.write('II');out.writeUInt16LE(42,2);out.writeUInt32LE(8,4);let pos=8;
 const ifd0=[[0x10f,2,make],[0x110,2,model],[0x8769,4,0]],exif=[[0xa434,2,lens],...(params?[[0x8827,3,800],[0x829d,5,[28,10]],[0x829a,5,[1,250]]]:[])];
 const exifPos=8+2+12*ifd0.length+4;let dataPos=exifPos+2+12*exif.length+4;ifd0[2][2]=exifPos;
 for(const [entries,start] of [[ifd0,8],[exif,exifPos]]){out.writeUInt16LE(entries.length,start);entries.forEach(([tag,type,value],i)=>{const o=start+2+i*12;out.writeUInt16LE(tag,o);out.writeUInt16LE(type,o+2);const bytes=type===2?Buffer.from(value+'\0'):null,count=bytes?bytes.length:1;out.writeUInt32LE(count,o+4);if(bytes){if(bytes.length<=4)bytes.copy(out,o+8);else{out.writeUInt32LE(dataPos,o+8);bytes.copy(out,dataPos);dataPos+=bytes.length;}}else if(type===5){out.writeUInt32LE(dataPos,o+8);out.writeUInt32LE(value[0],dataPos);out.writeUInt32LE(value[1],dataPos+4);dataPos+=8;}else out.writeUInt32LE(value,o+8);});}
 const app=Buffer.concat([Buffer.from('Exif\0\0'),out.subarray(0,dataPos)]),len=Buffer.alloc(2);len.writeUInt16BE(app.length+2);return Buffer.concat([jpeg.subarray(0,2),Buffer.from([255,225]),len,app,jpeg.subarray(2)]);
}
(async()=>{
 const browser=await pw.chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url().slice(0,200)+' '+r.failure().errorText));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
 await page.goto(base+'polaroid.html');await page.evaluate(()=>Promise.all([logoReady,modelLogoReady]));
 const jpeg=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=2000;c.height=3000;const g=c.getContext('2d');g.fillStyle='#456970';g.fillRect(0,0,c.width,c.height);return c.toDataURL('image/jpeg').split(',')[1]}),'base64');
 const fixtures=[['NIKON CORPORATION','NIKON Z5 II','NIKKOR Z 24-70mm f/4 S'],['NIKON CORPORATION','niKoN : Z6','NIKKOR Z 40mm f/2'],['FUJIFILM','X-T50','XF 35mm F1.4 R'],['Google','Pixel 8 Pro','Pixel back camera 2.23mm'],['Apple','iPhone 15 Pro','iPhone back triple camera'],['SONY','ILCE-7CM2','FE 24-105mm F4 G OSS'],['Unknown','Unknown Camera','Mystery lens']];
 await page.locator('#file').setInputFiles(fixtures.map(([make,model,lens],i)=>({name:'fixture-'+i+'.jpg',mimeType:'image/jpeg',buffer:exifJpeg(jpeg,make,model,lens,i!==6)})));
 await page.waitForFunction(()=>itemsList.length===7&&!addingFiles);await page.evaluate(()=>prepareTextFonts(activeState));
 const states=await page.evaluate(()=>itemsList.map(s=>({brand:s.cameraBrand,model:s.cameraModel,phone:s.isPhone,lens:s.lens,raw:s.rawExif,parts:s.cameraParts})));
 assert.equal(states[0].brand,'NIKON');assert.equal(states[0].model,'Z5 II');assert.equal(states[1].model,'Z6');assert.equal(states[0].raw.make,'NIKON CORPORATION');assert.equal(states[0].raw.model,'NIKON Z5 II');assert.equal(states[2].model,'X-T50');assert(states[3].phone&&states[4].phone);assert(!states[5].phone&&!states[6].phone);
 async function select(i){await page.evaluate(i=>{currentIndex=i;activeState=itemsList[i];syncUIFromState();drawAll(false)},i)}
 for(const i of [3,4,5,6,0]){await select(i);assert.equal(await page.locator('#lens').isVisible(),![3,4].includes(i));assert.equal(await page.locator('#show-exp').isVisible(),i!==6);const texts=await page.evaluate(()=>{const ctx=$('#mainCanvas').getContext('2d'),orig=ctx.fillText,seen=[];ctx.fillText=function(t,...a){seen.push(t);return orig.call(this,t,...a)};drawAll(false);ctx.fillText=orig;return seen});if([3,4].includes(i))assert(!texts.some(t=>t.includes('back camera')||t.includes('triple camera')));}
 await page.selectOption('#camera-brand','manual');await page.fill('#camera-brand-text','NIKON CORPORATION');await page.selectOption('#camera-select','manual');await page.fill('#cam','niKON / Z6');assert.equal(await page.evaluate(()=>activeState.cameraModel),'Z6');assert.equal(await page.evaluate(()=>activeState.cameraBrand),'NIKON');
 for(const [key,name] of [['nikon-z5ii','Z5 II'],['nikon-z6','Z6'],['fuji-xt50','X-T50']]){await page.selectOption('#camera-select',key);assert.equal(await page.evaluate(()=>activeState.cameraModel),name);assert(!await page.locator('#cam').isVisible());}
 await page.selectOption('#camera-brand','auto');await page.selectOption('#camera-select','auto');assert.equal(await page.evaluate(()=>activeState.cameraModel),'Z5 II');
 await page.evaluate(()=>{activeState.font='genryu-el';activeState.noteFont='sans';syncUIFromState()});assert.equal(await page.inputValue('#font'),'huninn');assert.equal(await page.inputValue('#note-font'),'huninn');
 const options=await page.locator('#font option').evaluateAll(xs=>xs.map(x=>x.value));assert(!options.some(x=>['sans','genryu-el','genryu-l','genryu-r'].includes(x)));assert.equal(options.length,12);
 await page.evaluate(async()=>{activeState.source=Object.assign(document.createElement('canvas'),{width:4000,height:3000});activeState.source.getContext('2d').fillRect(0,0,4000,3000);activeState.frameStyle='tint';activeState.cameraBrandChoice='sony';activeState.cameraModelChoice='sony-a7cii';activeState.lens='FE 24-105mm F4 G OSS';syncUIFromState();syncStateFromUI();await prepareTextFonts(activeState);drawAll(false);});
 const perf=await page.evaluate(async()=>{const counts={sync:0,exif:0,phone:0,normalize:0,sample:0,draw:0};const wrap=(fn,key)=>(...args)=>{counts[key]++;return fn(...args)};syncStateFromUI=wrap(syncStateFromUI,'sync');readExif=wrap(readExif,'exif');isPhoneExif=wrap(isPhoneExif,'phone');refreshCameraDisplay=wrap(refreshCameraDisplay,'normalize');sampleTint=wrap(sampleTint,'sample');const times=[];const orig=drawAll;drawAll=(...args)=>{let t=performance.now();orig(...args);times.push(performance.now()-t);counts.draw++};const input=$('#color');const events=[];for(let i=0;i<80;i++){input.value='#'+(0x120000+i*1234).toString(16);let t=performance.now();input.dispatchEvent(new Event('input',{bubbles:true}));events.push(performance.now()-t);}await new Promise(requestAnimationFrame);const burst={...counts};for(let i=0;i<60;i++){input.value='#'+(0x225500+i*371).toString(16);input.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(requestAnimationFrame)}input.value='#2468ac';input.dispatchEvent(new Event('change',{bubbles:true}));const final=activeState.color,png=$('#mainCanvas').toDataURL();drawAll(false);return {events:80,eventTotalMs:events.reduce((a,b)=>a+b),eventMeanMs:events.reduce((a,b)=>a+b)/80,drawMeanMs:times.reduce((a,b)=>a+b)/times.length,drawMaxMs:Math.max(...times),burst,counts,final,exactFinal:png===$('#mainCanvas').toDataURL()}});
 assert.equal(perf.final,'#2468ac');assert(perf.exactFinal);for(const k of ['sync','exif','phone','normalize','sample'])assert.equal(perf.counts[k],0,k);assert(perf.burst.draw<=1);const before=JSON.parse(fs.readFileSync(path.join(root,'qa','color-before.json'),'utf8'));assert(perf.eventMeanMs<before.meanMs/5);
 // Load each retained face and inspect all 48 sizes with CJK and Latin metrics.
 const metrics=await page.evaluate(async options=>{await Promise.all(options.map(k=>requestTextFont(k,500,'旅行相機鏡頭 Aa 0123456789')));const c=document.createElement('canvas');c.width=1200;c.height=options.length*120;const g=c.getContext('2d');g.fillStyle='#f7f3ec';g.fillRect(0,0,c.width,c.height);const result=[];for(let r=0;r<options.length;r++){const key=options[r];for(let i=0;i<4;i++){const level=[12,14,18,22][i],size=fontSizeFor(key,level);g.fillStyle='#000';g.font='12px sans-serif';g.fillText(key+' '+['小','中','大','特大'][i],i*300+8,r*120+18);g.font=textFont(key,size*1.5,500);const m=g.measureText('旅行相機 Aa');g.fillText('旅行相機 Aa',i*300+8,r*120+65);g.font=textFont(key,size,500);g.fillText('f/2.8  1/250  ISO 800',i*300+8,r*120+103);result.push({key,level,size,height:m.actualBoundingBoxAscent+m.actualBoundingBoxDescent,loaded:document.fonts.check(textFont(key,16,500),'旅行相機 Aa')});}}return {result,png:c.toDataURL().split(',')[1],failed:[...failedFonts]};},options);
 fs.writeFileSync(path.join(root,'qa','font-size-sheet.png'),Buffer.from(metrics.png,'base64'));assert(metrics.result.every(x=>x.height>8&&x.loaded));assert.equal(metrics.failed.length,0);
 await select(0);await page.selectOption('#camera-brand','auto');await page.selectOption('#camera-select','auto');await page.selectOption('#show-exp','on');await page.fill('#note-text','東京旅行');await page.evaluate(()=>{activeState.aspect='instagram-story';activeState.frameStyle='white';syncUIFromState();drawAll(false)});
 const png=await page.evaluate(()=>$('#mainCanvas').toDataURL().split(',')[1]);fs.writeFileSync(path.join(root,'qa','story-new.png'),Buffer.from(png,'base64'));
 await page.locator('#text-settings').screenshot({path:path.join(root,'qa','desktop-fields.png')});
 await page.setViewportSize({width:390,height:844});await select(3);await page.locator('#text-settings').screenshot({path:path.join(root,'qa','mobile-fields.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const columns=await page.locator('#text-settings .row2').first().evaluate(x=>getComputedStyle(x).gridTemplateColumns);assert.equal(columns.split(' ').length,1);
 await page.goto(base+'index.html');assert((await page.title()).includes('富士'));await page.getByRole('link',{name:'拍立得工作室',exact:true}).click();assert((await page.title()).includes('拍立得'));await page.getByRole('link',{name:'富士食譜工具',exact:true}).click();assert((await page.title()).includes('富士'));
 const report={states,perf,before,fontMetrics:metrics.result,errors,checks:'EXIF fixtures, per-photo phone UI/render, source/presets/manual, fallback, 48 font sizes, responsive layout, exact final color, no import work during dragging, both navigation directions'};fs.writeFileSync(path.join(root,'qa','verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({perf,fontCount:metrics.result.length,errors},null,2));assert.deepEqual(errors,[]);await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1});
