const fs=require('fs'),p=require('path'),http=require('http'),assert=require('assert');const pw=require('C:/Users/KenSi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root=p.resolve(__dirname,'..');
(async()=>{const b=await pw.chromium.launch({channel:'msedge',headless:true});try{const page=await b.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://kensi_nas/homes/KenSi/'+encodeURIComponent('拍立得模擬器')+'/polaroid.html');await page.evaluate(async()=>{await Promise.all([logoReady,modelLogoReady]);const c=document.createElement('canvas');c.width=800;c.height=1200;c.getContext('2d').fillRect(0,0,800,1200);for(const key of ['nikon-z5ii','nikon-z6','fuji-xt50']){const st=createDefaultItemState();st.source=c;st.cameraBrandChoice=key.startsWith('nikon')?'nikon':'fujifilm';st.cameraModelChoice=key;st.cameraBrand=CAMERA_BRANDS[st.cameraBrandChoice];st.cameraModel=CAMERA_MODELS[key].text;st.lens='24-70mm';st.aspect='instagram-story';refreshCameraDisplay(st);itemsList.push(st);}currentIndex=0;activeState=itemsList[0];renderThumbnails();syncUIFromState();await prepareTextFonts(activeState);drawAll(false)});
 const alpha=await page.evaluate(()=>Object.fromEntries(['z5ii','z6','xt50'].map(key=>{const img=logoMasks[key],c=document.createElement('canvas');c.width=img.width*4;c.height=img.height*4;const g=c.getContext('2d');drawCameraMark(g,img,0,0,c.height,"#000000");const d=g.getImageData(0,0,c.width,c.height).data;let transparent=0,soft=0,red=0,white=0;for(let i=0;i<d.length;i+=4){if(!d[i+3])transparent++;else if(d[i+3]<255)soft++;if(d[i]>150&&d[i+1]<50&&d[i+2]<50&&d[i+3]>200)red++;if(d[i]>240&&d[i+1]>240&&d[i+2]>240&&d[i+3]>200)white++;}return [key,{transparent,soft,red,white}]})));for(const a of Object.values(alpha)){assert(a.transparent>100);assert(a.soft>100);assert.equal(a.white,0)}assert(alpha.z5ii.red>100);
 const [png]=await Promise.all([page.waitForEvent('download'),page.click('#save')]);await png.saveAs(p.join(root,'qa','export-single.png'));const pngBytes=fs.readFileSync(p.join(root,'qa','export-single.png'));assert.equal(pngBytes.readUInt32BE(16),1080);assert.equal(pngBytes.readUInt32BE(20),1920);
 const before=await page.evaluate(()=>$('#mainCanvas').toDataURL());const [zip]=await Promise.all([page.waitForEvent('download'),page.click('#save-all')]);await zip.saveAs(p.join(root,'qa','export-batch.zip'));assert.equal(await page.evaluate(()=>$('#mainCanvas').toDataURL()),before);
 const entries=await page.evaluate(async data=>{const zip=await JSZip.loadAsync(Uint8Array.from(atob(data),x=>x.charCodeAt(0)),{checkCRC32:true});const sizes=[];for(const name of Object.keys(zip.files)){const bytes=await zip.files[name].async('uint8array');const image=await createImageBitmap(new Blob([bytes]));sizes.push({name,width:image.width,height:image.height});image.close();}return sizes},fs.readFileSync(p.join(root,'qa','export-batch.zip')).toString('base64'));assert.equal(entries.length,3);assert(entries.every(x=>x.width===1080&&x.height===1920));
 await page.click('#stageToggle');await page.locator('#camera-brand').scrollIntoViewIfNeeded();await page.screenshot({path:p.join(root,'qa','mobile-viewport.png')});
 const server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\//,'')||'index.html';const target=p.resolve(root,rel);if(!target.startsWith(root)){res.writeHead(403).end();return;}fs.readFile(target,(e,buf)=>{if(e){res.writeHead(404).end();return}res.setHeader('Content-Type',target.endsWith('.html')?'text/html; charset=utf-8':target.endsWith('.js')?'text/javascript':target.endsWith('.svg')?'image/svg+xml':'application/octet-stream');res.end(buf)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/';try{const web=await b.newPage();await web.goto(url+'polaroid.html');await web.evaluate(async()=>{await caches.open('fuji-recipe-v24');await caches.open('unrelated-app-cache');await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready});await web.waitForFunction(async()=>!(await caches.keys()).includes('fuji-recipe-v24'));assert(await web.evaluate(async()=>(await caches.keys()).includes('unrelated-app-cache')));await web.goto(url);assert((await web.title()).includes('富士'));await web.getByRole('link',{name:'拍立得工作室',exact:true}).click();assert((await web.title()).includes('拍立得'));await web.close()}finally{server.close()}
 const report={alpha,entries,exportRestoresPreview:true,cacheCleanupScoped:true,errors};fs.writeFileSync(p.join(root,'qa','export-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));assert.deepEqual(errors,[]);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
